name: devops-project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Short SHA
        id: short_sha
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
          echo "short_sha=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
      - name: Build Docker image
        run: |
          docker build -t bingbong-maker/devops-project:${{ steps.short_sha.outputs.short_sha }} .    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Dockerhub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: bingbong-maker/devops-project:${{ steps.short_sha.outputs.short_sha }}
      - name: Configrue Git Author
        run: |
          git config --local user.email "hello@bingbongmaker.com"
          git config --local user.name "bingbongmaker"    
      - name: Update Helm Chart with new image tag
        run: |
          sed -i "s/tag:.*/tag: ${{ steps.short_sha.outputs.short_sha }}/" ./complete-devops-project-time-printer/values.yaml
          git add ./complete-devops-project-time-printer/values.yaml
          git commit -m "Updated image tag to ${{ steps.short_sha.outputs.short_sha }}"
          git push   
