name: devops-project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set Short SHA
        id: short_sha
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
          echo "short_sha=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
      - name: Build Docker image
        run: |
          docker build -t bingbong-maker/devops-project:${{ steps.short_sha.outputs.short_sha }} .    
      - name: Login to Dockerhub
        run: | 
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Push to Dockerhub
        run: |
          docker push bingbong-maker/devops-project:${{ steps.short_sha.outputs.short_sha }}
